### ISSUE TITLE
Tsuki

### ISSUE THREAD

**Issue by f0x52** [lainchan/lainchan#90]
1. `tsuki.css` is not in the git repo, altough it's here: https://lainchan.org/stylesheets/tsuki.css
2. `tsuki.css` doesn't work properly since the font declaration isn't there.
I made a fixed version at https://f.0x52.eu/tsuki.css
basically a 
```css
@font-face {
	font-family: "Normal";
	src: url(/PixelOperator.ttf);
}
```
at the start, and then also making `PixelOperator.ttf` accessible somewhere
